package main

import (
	"fmt"
	"io/ioutil"
	"log"
	"math/rand"
	"net"
	"net/http"
	"os"
	"time"

	_ "embed"

	"github.com/go-echarts/go-echarts/v2/charts"
	"github.com/go-echarts/go-echarts/v2/opts"
)

// func generateBarItems(data []int) []opts.BarData {
// 	items := make([]opts.BarData, len(data))
// 	for _, d := range data {
// 		items = append(items, opts.BarData{Value: d})
// 	}
// 	return items
// }

func generateBarItems() []opts.BarData {
	items := make([]opts.BarData, 0)
	for i := 0; i < 7; i++ {
		items = append(items, opts.BarData{Value: rand.Intn(300)})
	}
	return items
}

// https://medium.com/@nate510/don-t-use-go-s-default-http-client-4804cb19f779
var netTransport = &http.Transport{
	Dial: (&net.Dialer{
		Timeout: 5 * time.Second,
	}).Dial,
	TLSHandshakeTimeout: 5 * time.Second,
}
var netClient = &http.Client{
	Timeout:   time.Second * 10,
	Transport: netTransport,
}

const (
	openAPIURL = "http://openapi.data.go.kr/openapi/service/rest/Covid19/getCovid19InfStateJson"
)

func get3WeeksRange() (string, string) {
	dateFormat := "20060102"
	cTime := time.Now()
	endDate := cTime.Format(dateFormat)
	startDate := cTime.AddDate(0, 0, -23).Format(dateFormat) // I need 21 days, but I have 23 days just in case
	fmt.Printf("startDate %v, endDate %v\n", startDate, endDate)
	return startDate, endDate
}

func getCoronaData() ([]byte, error) {

	// make request with query https://stackoverflow.com/a/30657518/6513756
	req, err := http.NewRequest("GET", openAPIURL, nil)
	if err != nil {
		return nil, err
	}

	startDate, endDate := get3WeeksRange()
	q := req.URL.Query()
	q.Add("serviceKey", serviceKey)
	q.Add("pageNo", "1")
	q.Add("numOfRows", "25") // I will have max 23 days result
	q.Add("startCreateDt", startDate)
	q.Add("endCreateDt", endDate)
	req.URL.RawQuery = q.Encode()

	fmt.Println("query:", q)
	fmt.Println("url:", req.URL.RequestURI())

	resp, err := netClient.Do(req)
	if err != nil {
		return nil, err
	}
	defer resp.Body.Close()

	// response
	if resp.StatusCode != http.StatusOK {
		return nil, err
	}

	bodyBytes, err := ioutil.ReadAll(resp.Body)
	if err != nil {
		return nil, err
	}

	return bodyBytes, nil
}

func weeklyHandler(w http.ResponseWriter, r *http.Request) {

	// if the last creation of the html is over 2 min
	// - (24*60*60)/1000 = 86.4 seconds // 1000 request per day
	b, err := getCoronaData()
	if err != nil {
		log.Println(err)
		// need return code
		return
	}
	fmt.Println(string(b))

	// create a new bar instance
	bar := charts.NewBar()
	// set some global options like Title/Legend/ToolTip or anything else
	bar.SetGlobalOptions(
		charts.WithTitleOpts(opts.Title{
			Title:    "My first bar chart generated by go-echarts",
			Subtitle: "It's extremely easy to use, right?",
		}),
		charts.WithLegendOpts(opts.Legend{Show: true}),
	)

	// Put data into instance
	bar.SetXAxis([]string{"Mon", "Tue", "Wed", "Thu", "Fri", "Sat", "Sun"}).
		AddSeries("Category A", generateBarItems()).
		AddSeries("Category B", generateBarItems()).
		AddSeries("Category C", generateBarItems())
	// Where the magic happens
	f, _ := os.Create("bar.html")
	bar.Render(f)

	htmlFile := "./bar.html"
	http.ServeFile(w, r, htmlFile)
}

const port = ":8081"

//go:embed coronaState.key
var serviceKey string

func main() {

	fmt.Println("service Key: ", serviceKey)
	http.HandleFunc("/", weeklyHandler)
	http.ListenAndServe(port, nil)
}
